In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dados = 'BaseDPEvolucaoMensalCisp.csv'
df = pd.read_csv(dados, encoding= 'latin1', sep= ';')

In [ ]:
# Exibe as primeiras linhas do dataframe (número de linhas definido entre os parênteses)
df.head()

In [ ]:
# Exibe as últimas linhas do dataframe (número de linhas definido entre os parênteses)
df.tail()

In [ ]:
#  df.groupby(variáveis qualitativas)[variáveis quantitativas].método de agrupamento quantitativo(sum()...).reset_index()
df_furto_celular_cisp = df.groupby('cisp')['furto_celular'].sum().reset_index()
df_furto_celular_cisp

In [ ]:
# Exibe informações gerais do dataframe
df.info()

In [ ]:
# Exibe dados estatísticos das colunas numéricas
df.describe()

In [ ]:
# Exibe o número de linhas e colunas do dataframe
df.shape

In [ ]:
# Exibe o nome das olunas do dataframe
df.columns

In [ ]:
# Exibe linhas do dataframe indicadas por índice
df.iloc[0:5]

In [ ]:
# Exibe linhas do dataframe que atendam uma condição
df_rj = df.loc[df['munic'] == 'Rio de Janeiro']

In [ ]:
df_rj.groupby('cisp')['furto_celular'].sum().reset_index()

In [ ]:
df_2024 = df.loc[df['ano'] == 2024]
df_2024.groupby('cisp')['pessoas_desaparecidas'].sum().reset_index()

In [ ]:
df_baixada_2020 = df.loc[(df['ano'] == 2020) & (df['regiao'] == 'Baixada Fluminense')]
df_baixada_2020.groupby('cisp')['pessoas_desaparecidas'].sum().reset_index()

In [ ]:
# ETL => Extract, Transform, Load

In [ ]:
dados_numpy = np.array([12, 15, 17, 20, 22, 25, 28, 30, 35, 40])

q1 = np.percentile(dados_numpy, 25)
q2 = np.percentile(dados_numpy, 50)
q3 = np.percentile(dados_numpy, 75)

print(f'Primeiro quartil (Q1): {q1}')
print(f'Segundo quartil (Q2): {q2}')
print(f'Terceiro quartil (Q3): {q3}')

In [44]:
array_furto_celular = np.array(df_furto_celular_cisp['furto_celular'])

q1_furto_celular = np.percentile(array_furto_celular, 25)
q2_furto_celular = np.percentile(array_furto_celular, 50)
q3_furto_celular = np.percentile(array_furto_celular, 75)
media_furto_celular = np.mean(array_furto_celular)
mediana_furto_celular = np.median(array_furto_celular)
distancia_furto_celular = (media_furto_celular - mediana_furto_celular) / mediana_furto_celular

print(f'Primeiro quartil (Q1): {q1_furto_celular}')
print(f'Segundo quartil (Q2): {q2_furto_celular}') # Mediana
print(f'Terceiro quartil (Q3): {q3_furto_celular}')
print(f'Média: {media_furto_celular}')
print(f'Mediana: {mediana_furto_celular}')
print(f'Distância entre média e mediana: {distancia_furto_celular}')

Primeiro quartil (Q1): 451.25
Segundo quartil (Q2): 1675.5
Terceiro quartil (Q3): 4580.0
Média: 3422.978260869565
Mediana: 1675.5
Distância entre média e mediana: 1.042959272378135

In [ ]:
df_menor_q1_furto_celulares = df_furto_celular_cisp.loc[df_furto_celular_cisp['furto_celular'] < q1_furto_celular]

df_menor_q1_furto_celulares = df_menor_q1_furto_celulares.sort_values(by='furto_celular')
#df_menor_q1_furto_celulares = df_menor_q1_furto_celulares.sort_values(by='furto_celular', ascending= False)

df_menor_q1_furto_celulares

In [ ]:
df_capital_2020 = df.loc[(df['ano'] == 2020) & (df['regiao'] == 'Capital')]
df_apreenssao_menores_capital_2020 = df_capital_2020.groupby('cisp')['aaapai'].sum().reset_index()

array_apreensao_menores_capital_2020 = np.array(df_apreenssao_menores_capital_2020['aaapai'])

q1_apreensao_menores_capital_2020 = np.percentile(array_apreensao_menores_capital_2020, 25)
q2_apreensao_menores_capital_2020 = np.percentile(array_apreensao_menores_capital_2020, 50)
q3_apreensao_menores_capital_2020 = np.percentile(array_apreensao_menores_capital_2020, 75)

In [ ]:
df_maior_q3_apreensao_menores_capital_2020 = df_apreenssao_menores_capital_2020.loc[df_apreenssao_menores_capital_2020['aaapai'] > q3_apreensao_menores_capital_2020]
df_maior_q3_apreensao_menores_capital_2020 = df_maior_q3_apreensao_menores_capital_2020.sort_values(by='aaapai', ascending=False)

df_maior_q3_apreensao_menores_capital_2020

In [43]:
gestao_atual = [2023, 2024,  2025, 2026]
df_interior_atual = df.loc[(df['regiao'] == 'Interior') & (df['ano'].isin(gestao_atual))]
df_interior_atual

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
32305,70,1,2023,2023m01,35,4,Tanguá,3305752,Interior,0,...,3.0,0.0,8,0,0,0,0,0,68,3
32306,71,1,2023,2023m01,35,4,Itaboraí,3301900,Interior,1,...,6.0,0.0,26,2,0,0,0,0,454,3
32317,88,1,2023,2023m01,10,5,Barra do Pirai,3300308,Interior,2,...,8.0,0.0,22,1,0,0,0,0,261,3
32318,89,1,2023,2023m01,37,5,Resende,3304201,Interior,6,...,10.0,2.0,37,4,0,0,0,0,516,3
32319,90,1,2023,2023m01,28,5,Barra Mansa,3300407,Interior,6,...,8.0,0.0,61,0,0,0,0,0,480,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37309,159,1,2026,2026m01,35,4,Cachoeiras de Macacu,3300803,Interior,1,...,2.0,0.0,37,1,0,0,0,0,157,2
37310,165,1,2026,2026m01,33,5,Mangaratiba,3302601,Interior,0,...,3.0,0.0,32,0,0,0,0,0,234,2
37311,166,1,2026,2026m01,33,5,Angra dos Reis,3300100,Interior,2,...,10.0,0.0,98,9,1,0,0,0,713,2
37312,167,1,2026,2026m01,43,5,Paraty,3303807,Interior,1,...,3.0,0.0,25,2,0,0,0,0,258,2
37313,168,1,2026,2026m01,28,5,Rio Claro,3304409,Interior,1,...,0.0,0.0,3,0,0,0,0,0,57,2

In [53]:
regiao_metropolitana = ['Belford Roxo', 'Cachoeiras de Macacu', 'Duque de Caxias', 'Guapimirim', 'Itaboraí', 'Itaguaí', 'Japeri', 'Magé', 'Maricá', 'Mesquita', 'Nilópolis', 'Niterói', 'Nova Iguaçu', 'Paracambi', 'Petrópolis', 'Queimados', 'Rio Bonito', 'Rio de Janeiro', 'São Gonçalo', 'São João de Meriti', 'Seropédica', 'Tanguá']
df_metropolitana_2024 = df.loc[(df['ano'] == 2024) & (df['munic'].isin(regiao_metropolitana))]
df_furto_cel_rm_24 = df_metropolitana_2024.groupby('cisp')['furto_celular'].sum().reset_index()

array_furtos_celular_metr_2024 = np.array(df_furto_cel_rm_24['furto_celular'])
media_furto_celular_metr_2024 = np.mean(array_furtos_celular_metr_2024)
mediana_furto_celular_metr_2024 = np.median(array_furtos_celular_metr_2024)
distancia_furto_celular_metr_2024 = (media_furto_celular_metr_2024 - mediana_furto_celular_metr_2024) / mediana_furto_celular_metr_2024

df_furto_cel_rm_24

    cisp  furto_celular
0      1           1104
1      4           1500
2      5           2259
3      6            580
4      7            222
..   ...            ...
71    82            204
72   105            127
73   106            161
74   119             36
75   159             17

[76 rows x 2 columns]

In [ ]:
print(f'Média de furtos de celular na região metropolitana: {media_furto_celular_metr_2024}')
print(f'Mediana de furtos de celular na região metropolitana: {mediana_furto_celular_metr_2024}')
print(f'Distância entre média e mediana: {distancia_furto_celular_metr_2024}')
print(f'Distância em porcentagem: {round(distancia_furto_celular_metr_2024, 2) * 100}%')

In [57]:
munic = df.groupby('munic').size().reset_index(name='Quantidade')
munic.to_csv('municipios.csv', index=False, sep=';')