In [ ]:
import pandas as pd
import numpy as np

In [50]:
dados = 'BaseDPEvolucaoMensalCisp.csv'
df = pd.read_csv(dados, encoding= 'latin1', sep= ';')

In [30]:
# Exibe as primeiras linhas do dataframe (número de linhas definido entre os parênteses)
df.head()

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3

In [ ]:
# Exibe as últimas linhas do dataframe (número de linhas definido entre os parênteses)
df.tail()

In [ ]:
#  df.groupby(variáveis qualitativas)[variáveis quantitativas].método de agrupamento quantitativo(sum()...).reset_index()
df_furto_celular_cisp = df.groupby('cisp')['furto_celular'].sum().reset_index()
df_furto_celular_cisp

In [ ]:
# Exibe informações gerais do dataframe
df.info()

In [ ]:
# Exibe dados estatísticos das colunas numéricas
df.describe()

In [ ]:
# Exibe o número de linhas e colunas do dataframe
df.shape

In [ ]:
# Exibe o nome das olunas do dataframe
df.columns

In [ ]:
# Exibe linhas do dataframe indicadas por índice
df.iloc[0:5]

In [ ]:
# Exibe linhas do dataframe que atendam uma condição
df_rj = df.loc[df['munic'] == 'Rio de Janeiro']

In [ ]:
df_rj.groupby('cisp')['furto_celular'].sum().reset_index()

In [ ]:
df_2024 = df.loc[df['ano'] == 2024]
df_2024.groupby('cisp')['pessoas_desaparecidas'].sum().reset_index()

In [ ]:
df_baixada_2020 = df.loc[(df['ano'] == 2020) & (df['regiao'] == 'Baixada Fluminense')]
df_baixada_2020.groupby('cisp')['pessoas_desaparecidas'].sum().reset_index()

In [ ]:
# ETL => Extract, Transform, Load

In [ ]:
dados_numpy = np.array([12, 15, 17, 20, 22, 25, 28, 30, 35, 40])

q1 = np.percentile(dados_numpy, 25)
q2 = np.percentile(dados_numpy, 50)
q3 = np.percentile(dados_numpy, 75)

print(f'Primeiro quartil (Q1): {q1}')
print(f'Segundo quartil (Q2): {q2}')
print(f'Terceiro quartil (Q3): {q3}')

In [32]:
array_furto_celular = np.array(df_furto_celular_cisp['furto_celular'])

q1_furto_celular = np.percentile(array_furto_celular, 25)
q2_furto_celular = np.percentile(array_furto_celular, 50)
q3_furto_celular = np.percentile(array_furto_celular, 75)
media_furto_celular = np.mean(array_furto_celular)
mediana_furto_celular = np.median(array_furto_celular)
distancia_furto_celular = (media_furto_celular - mediana_furto_celular) / mediana_furto_celular
iqr_furto_celular = q3_furto_celular - q1_furto_celular
lim_sup_furto_celular = q3_furto_celular + (1.5 * iqr_furto_celular)
lim_inf_furto_celular = q1_furto_celular - (1.5 * iqr_furto_celular)

print(f'Primeiro quartil (Q1): {q1_furto_celular}')
print(f'Segundo quartil (Q2): {q2_furto_celular}') # Mediana
print(f'Terceiro quartil (Q3): {q3_furto_celular}')
print(f'Média: {media_furto_celular}')
print(f'Mediana: {mediana_furto_celular}')
print(f'Distância entre média e mediana: {distancia_furto_celular}')
print(f'Distância em porcentagem: {distancia_furto_celular * 100}%')
print(f'Intervalo entre quartis (IQR): {iqr_furto_celular}')
print(f'Limite superior: {lim_sup_furto_celular}')
print(f'Limite inferior: {lim_inf_furto_celular}')

Primeiro quartil (Q1): 451.25
Segundo quartil (Q2): 1675.5
Terceiro quartil (Q3): 4580.0
Média: 3422.978260869565
Mediana: 1675.5
Distância entre média e mediana: 1.042959272378135
Distância em porcentagem: 104.29592723781349%
Intervalo entre quartis (IQR): 4128.75
Limite superior: 10773.125
Limite inferior: -5741.875

In [38]:
df_furto_celular_cisp_outliers = df_furto_celular_cisp.loc[df_furto_celular_cisp['furto_celular'] >= lim_sup_furto_celular]
df_furto_celular_cisp_outliers = df_furto_celular_cisp_outliers.sort_values(by='furto_celular', ascending=False)
df_furto_celular_cisp_outliers

    cisp  furto_celular
12    16          25480
2      5          23969
10    14          17633
8     12          16659
0      1          15487
5      9          14621
6     10          14370
14    18          13808
1      4          13700
28    32          12504
31    35          12007

In [ ]:
df_menor_q1_furto_celulares = df_furto_celular_cisp.loc[df_furto_celular_cisp['furto_celular'] < q1_furto_celular]

df_menor_q1_furto_celulares = df_menor_q1_furto_celulares.sort_values(by='furto_celular')
#df_menor_q1_furto_celulares = df_menor_q1_furto_celulares.sort_values(by='furto_celular', ascending= False)

df_menor_q1_furto_celulares

In [ ]:
df_capital_2020 = df.loc[(df['ano'] == 2020) & (df['regiao'] == 'Capital')]
df_apreenssao_menores_capital_2020 = df_capital_2020.groupby('cisp')['aaapai'].sum().reset_index()

array_apreensao_menores_capital_2020 = np.array(df_apreenssao_menores_capital_2020['aaapai'])

q1_apreensao_menores_capital_2020 = np.percentile(array_apreensao_menores_capital_2020, 25)
q2_apreensao_menores_capital_2020 = np.percentile(array_apreensao_menores_capital_2020, 50)
q3_apreensao_menores_capital_2020 = np.percentile(array_apreensao_menores_capital_2020, 75)

In [ ]:
df_maior_q3_apreensao_menores_capital_2020 = df_apreenssao_menores_capital_2020.loc[df_apreenssao_menores_capital_2020['aaapai'] > q3_apreensao_menores_capital_2020]
df_maior_q3_apreensao_menores_capital_2020 = df_maior_q3_apreensao_menores_capital_2020.sort_values(by='aaapai', ascending=False)

df_maior_q3_apreensao_menores_capital_2020

In [ ]:
gestao_atual = [2023, 2024,  2025, 2026]
df_interior_atual = df.loc[(df['regiao'] == 'Interior') & (df['ano'].isin(gestao_atual))]
df_interior_atual

In [ ]:
regiao_metropolitana = ['Belford Roxo', 'Cachoeiras de Macacu', 'Duque de Caxias', 'Guapimirim', 'Itaboraí', 'Itaguaí', 'Japeri', 'Magé', 'Maricá', 'Mesquita', 'Nilópolis', 'Niterói', 'Nova Iguaçu', 'Paracambi', 'Petrópolis', 'Queimados', 'Rio Bonito', 'Rio de Janeiro', 'São Gonçalo', 'São João de Meriti', 'Seropédica', 'Tanguá']
df_metropolitana_2024 = df.loc[(df['ano'] == 2024) & (df['munic'].isin(regiao_metropolitana))]
df_furto_cel_rm_24 = df_metropolitana_2024.groupby('cisp')['furto_celular'].sum().reset_index()

array_furtos_celular_metr_2024 = np.array(df_furto_cel_rm_24['furto_celular'])
media_furto_celular_metr_2024 = np.mean(array_furtos_celular_metr_2024)
mediana_furto_celular_metr_2024 = np.median(array_furtos_celular_metr_2024)
distancia_furto_celular_metr_2024 = (media_furto_celular_metr_2024 - mediana_furto_celular_metr_2024) / mediana_furto_celular_metr_2024

df_furto_cel_rm_24

In [ ]:
print(f'Média de furtos de celular na região metropolitana: {media_furto_celular_metr_2024}')
print(f'Mediana de furtos de celular na região metropolitana: {mediana_furto_celular_metr_2024}')
print(f'Distância entre média e mediana: {distancia_furto_celular_metr_2024}')
print(f'Distância em porcentagem: {round(distancia_furto_celular_metr_2024, 2) * 100}%')

In [ ]:
munic = df.groupby('munic').size().reset_index(name='Quantidade')
munic.to_csv('municipios.csv', index=False, sep=';')

In [40]:
df_rj.columns

Index(['cisp', 'mes', 'ano', 'mes_ano', 'aisp', 'risp', 'munic', 'mcirc',
       'regiao', 'hom_doloso', 'lesao_corp_morte', 'latrocinio', 'cvli',
       'hom_por_interv_policial', 'feminicidio', 'letalidade_violenta',
       'tentat_hom', 'tentativa_feminicidio', 'lesao_corp_dolosa', 'estupro',
       'hom_culposo', 'lesao_corp_culposa', 'roubo_transeunte',
       'roubo_celular', 'roubo_em_coletivo', 'roubo_rua', 'roubo_veiculo',
       'roubo_carga', 'roubo_comercio', 'roubo_residencia', 'roubo_banco',
       'roubo_cx_eletronico', 'roubo_conducao_saque', 'roubo_apos_saque',
       'roubo_bicicleta', 'outros_roubos', 'total_roubos', 'furto_veiculos',
       'furto_transeunte', 'furto_coletivo', 'furto_celular',
       'furto_bicicleta', 'outros_furtos', 'total_furtos', 'sequestro',
       'extorsao', 'sequestro_relampago', 'estelionato', 'apreensao_drogas',
       'posse_drogas', 'trafico_drogas', 'apreensao_drogas_sem_autor',
       'recuperacao_veiculos', 'apf', 'aaapai', 'cmp', 'cmba', 'ameaca',
       'pessoas_desaparecidas', 'encontro_cadaver', 'encontro_ossada',
       'pol_militares_mortos_serv', 'pol_civis_mortos_serv',
       'registro_ocorrencias', 'fase'],
      dtype='str')

In [43]:
df_rj['ocorrencias_veiculos'] = df_rj['roubo_veiculo'] + df_rj['furto_veiculos']
df_rj_cisp_veiculos = df_rj.groupby('cisp')['ocorrencias_veiculos'].sum().reset_index().sort_values(by='ocorrencias_veiculos', ascending=False)
df_rj_cisp_veiculos.head()

    cisp  ocorrencias_veiculos
23    27                 39450
30    34                 37102
31    35                 33724
35    39                 32945
34    38                 26297

In [45]:
array_rj_cisp_veiculos = np.array(df_rj_cisp_veiculos['ocorrencias_veiculos'])
q1_rj_cisp_veiculos = np.percentile(array_rj_cisp_veiculos, 25)
q2_rj_cisp_veiculos = np.percentile(array_rj_cisp_veiculos, 50)
q3_rj_cisp_veiculos = np.percentile(array_rj_cisp_veiculos, 75)
media_rj_cisp_veiculos = np.mean(array_rj_cisp_veiculos)
mediana_rj_cisp_veiculos = np.median(array_rj_cisp_veiculos)
distancia_rj_cisp_veiculos = (media_rj_cisp_veiculos - mediana_rj_cisp_veiculos) / mediana_rj_cisp_veiculos
iqr_rj_cisp_veiculos = q3_rj_cisp_veiculos - q1_rj_cisp_veiculos
lim_sup_rj_cisp_veiculos = q3_rj_cisp_veiculos + (1.5 * iqr_rj_cisp_veiculos)
lim_inf_rj_cisp_veiculos = q1_rj_cisp_veiculos - (1.5 * iqr_rj_cisp_veiculos)

print(f'Primeiro quartil (Q1): {q1_rj_cisp_veiculos}')
print(f'Segundo quartil (Q2): {q2_rj_cisp_veiculos}') # Mediana
print(f'Terceiro quartil (Q3): {q3_rj_cisp_veiculos}')
print(f'Média: {media_rj_cisp_veiculos}')
print(f'Mediana: {mediana_rj_cisp_veiculos}')
print(f'Distância entre média e mediana: {distancia_rj_cisp_veiculos}')
print(f'Distância em porcentagem: {distancia_rj_cisp_veiculos * 100}%')
print(f'Intervalo entre quartis (IQR): {iqr_rj_cisp_veiculos}')
print(f'Limite superior: {lim_sup_rj_cisp_veiculos}')
print(f'Limite inferior: {lim_inf_rj_cisp_veiculos}')

Primeiro quartil (Q1): 5093.25
Segundo quartil (Q2): 12824.5
Terceiro quartil (Q3): 18242.75
Média: 14116.47619047619
Mediana: 12824.5
Distância entre média e mediana: 0.10074281184265982
Distância em porcentagem: 10.074281184265981%
Intervalo entre quartis (IQR): 13149.5
Limite superior: 37967.0
Limite inferior: -14631.0

In [46]:
outliers_rj_cisp_veiculos = df_rj_cisp_veiculos.loc[df_rj_cisp_veiculos['ocorrencias_veiculos'] >= lim_sup_rj_cisp_veiculos]
outliers_rj_cisp_veiculos

    cisp  ocorrencias_veiculos
23    27                 39450

In [54]:
max_ano = max(df['ano'])
df_decada = df.loc[df['ano'] > max_ano - 10]
df_decada

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
22357,1,1,2017,2017m01,5,1,Rio de Janeiro,3304557,Capital,0,...,4.0,0.0,12,0,0,0,0,0,375,3
22358,4,1,2017,2017m01,5,1,Rio de Janeiro,3304557,Capital,1,...,19.0,1.0,20,2,1,0,0,0,630,3
22359,5,1,2017,2017m01,5,1,Rio de Janeiro,3304557,Capital,0,...,17.0,3.0,26,1,0,0,0,0,836,3
22360,6,1,2017,2017m01,4,1,Rio de Janeiro,3304557,Capital,1,...,11.0,0.0,18,2,0,0,0,0,482,3
22361,7,1,2017,2017m01,5,1,Rio de Janeiro,3304557,Capital,3,...,4.0,0.0,10,0,0,0,0,0,230,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37309,159,1,2026,2026m01,35,4,Cachoeiras de Macacu,3300803,Interior,1,...,2.0,0.0,37,1,0,0,0,0,157,2
37310,165,1,2026,2026m01,33,5,Mangaratiba,3302601,Interior,0,...,3.0,0.0,32,0,0,0,0,0,234,2
37311,166,1,2026,2026m01,33,5,Angra dos Reis,3300100,Interior,2,...,10.0,0.0,98,9,1,0,0,0,713,2
37312,167,1,2026,2026m01,43,5,Paraty,3303807,Interior,1,...,3.0,0.0,25,2,0,0,0,0,258,2
37313,168,1,2026,2026m01,28,5,Rio Claro,3304409,Interior,1,...,0.0,0.0,3,0,0,0,0,0,57,2

In [55]:
df_decada_regiao_furto_veiculo = df_decada.groupby('regiao')['furto_veiculos'].sum().reset_index().sort_values(by='furto_veiculos', ascending=False)
df_decada_regiao_furto_veiculo

                          regiao  furto_veiculos
1                        Capital           67139
0             Baixada Fluminense           36978
4                       Interior           22261
2  Grande NiterÃÂÃÂÃÂÃÂ³i           14800
3                 Grande Niterói            2816

In [60]:
array_dec_reg_fur_vei = np.array(df_decada_regiao_furto_veiculo['furto_veiculos'])
q1_dec_reg_fur_vei = np.percentile(array_dec_reg_fur_vei, 25)
q2_dec_reg_fur_vei = np.percentile(array_dec_reg_fur_vei, 50)
q3_dec_reg_fur_vei = np.percentile(array_dec_reg_fur_vei, 75)
media_dec_reg_fur_vei = np.mean(array_dec_reg_fur_vei)
mediana_dec_reg_fur_vei = np.median(array_dec_reg_fur_vei)
distancia_dec_reg_fur_vei = (media_dec_reg_fur_vei - mediana_dec_reg_fur_vei) / mediana_dec_reg_fur_vei
iqr_dec_reg_fur_vei = q3_dec_reg_fur_vei - q1_dec_reg_fur_vei
lim_sup_dec_reg_fur_vei = q3_dec_reg_fur_vei + (1.5 * iqr_dec_reg_fur_vei)
lim_inf_dec_reg_fur_vei = q1_dec_reg_fur_vei - (1.5 * iqr_dec_reg_fur_vei)

print(f'Primeiro quartil (Q1): {q1_dec_reg_fur_vei}')
print(f'Segundo quartil (Q2): {q2_dec_reg_fur_vei}') # Mediana
print(f'Terceiro quartil (Q3): {q3_dec_reg_fur_vei}')
print(f'Média: {media_dec_reg_fur_vei}')
print(f'Mediana: {mediana_dec_reg_fur_vei}')
print(f'Distância entre média e mediana: {distancia_dec_reg_fur_vei}')
print(f'Distância em porcentagem: {distancia_dec_reg_fur_vei * 100}%')
print(f'Intervalo entre quartis (IQR): {iqr_dec_reg_fur_vei}')
print(f'Limite superior: {lim_sup_dec_reg_fur_vei}')
print(f'Limite inferior: {lim_inf_dec_reg_fur_vei}')

Primeiro quartil (Q1): 14800.0
Segundo quartil (Q2): 22261.0
Terceiro quartil (Q3): 36978.0
Média: 28798.8
Mediana: 22261.0
Distância entre média e mediana: 0.29368851354386594
Distância em porcentagem: 29.368851354386592%
Intervalo entre quartis (IQR): 22178.0
Limite superior: 70245.0
Limite inferior: -18467.0

In [61]:
outliers_decada_regiao_furto_veiculo = df_decada_regiao_furto_veiculo.loc[df_decada_regiao_furto_veiculo['furto_veiculos'] >= lim_sup_dec_reg_fur_vei]
outliers_decada_regiao_furto_veiculo

Empty DataFrame
Columns: [regiao, furto_veiculos]
Index: []