In [6]:
import pandas as pd

In [5]:
dados = 'vendas_vestuario_revisao.csv'
df = pd.read_csv(dados)

df.head()

  vendedor          produto  quantidade  valor_unitario
0  Edmundo    Camisa Social           2          217.87
1    Marta          Legging           2           76.57
2  Roberto      Calça Jeans           4          177.24
3  Roberto  Camiseta Básica           3           74.81
4   Junior          Legging           6          172.72

In [7]:
df['valor_vendido'] = df['quantidade'] * df['valor_unitario']
df

   vendedor          produto  quantidade  valor_unitario  valor_vendido
0   Edmundo    Camisa Social           2          217.87         435.74
1     Marta          Legging           2           76.57         153.14
2   Roberto      Calça Jeans           4          177.24         708.96
3   Roberto  Camiseta Básica           3           74.81         224.43
4    Junior          Legging           6          172.72        1036.32
..      ...              ...         ...             ...            ...
95  Roberto      Camisa Polo           3          145.74         437.22
96    Marta   Vestido Casual           2          207.33         414.66
97    Marta   Vestido Casual           4          236.13         944.52
98    Dulce    Jaqueta Jeans           4          384.26        1537.04
99    Marta          Legging           4          114.32         457.28

[100 rows x 5 columns]

In [8]:
df_vendido_vendedor = df.groupby('vendedor')['valor_vendido'].sum().reset_index().sort_values(by='valor_vendido')
df_vendido_vendedor

  vendedor  valor_vendido
1  Edmundo       10438.38
4  Roberto       11801.67
2   Junior       13575.26
0    Dulce       16849.41
3    Marta       17816.03