In [71]:
import pandas as pd
import numpy as np
pd.set_option('display.float_format', '{:.2f}'.format)

In [72]:
def agrupar_soma(df, qual, quant='Valor de Venda', menorMaior=False):
    return df.groupby(qual)[quant].sum().reset_index().sort_values(by=quant, ascending=menorMaior)

In [73]:
def aplicar_loc(df, col_condicao, valor_condicao, sinal):
    if sinal == '==':
        return df.loc[df[col_condicao] == valor_condicao]
    elif sinal == '>':
        return df.loc[df[col_condicao] > valor_condicao]
    elif sinal == '<':
        return df.loc[df[col_condicao] < valor_condicao]
    else:
        print('Operação Inválida!')
        return

In [74]:
def criar_array(df, coluna='Valor de Venda'):
    return np.array(df[coluna])

In [75]:
def calcular_quartis(df, coluna='Valor de Venda'):
    array = criar_array(df, coluna)
    q1 = np.percentile(array, 25)
    q2 = np.percentile(array, 50)
    q3 = np.percentile(array, 75)

    return [q1, q2, q3]

In [76]:
def calcular_distancia(df, coluna='Valor de Venda'):
    array = criar_array(df, coluna)
    media = np.mean(array)
    mediana = np.median(array)

    return (media - mediana) / mediana

In [77]:
def calcular_limites(df, coluna='Valor de Venda'):
    quartis = calcular_quartis(df, coluna)

    iqr = quartis[2] - quartis[0]

    lim_sup = quartis[2] + (1.5 * iqr)
    lim_inf = quartis[0] - (1.5 * iqr)

    return [lim_sup, lim_inf]

In [78]:
def mostrar_dist_lim(dist, lim):
    print(f'Distância: {dist}')
    print(f'Limite Superior: {lim[0]}')
    print(f'Limite Inferior: {lim[1]}')

In [79]:
dados = '../csv/CARAMELO.csv'
df = pd.read_csv(dados, sep=';')
df.head()

,ID Venda,Loja,ID Loja,Estado Loja,Cidade Loja,Nome Cliente,ID Cliente,Sexo,Idade,Estado Cliente,Cidade Cliente,ID Produto,Categoria Produto,Marca,Data da Compra,Data da Entrega,Metodo de Pagamento,Produto,Valor de Venda
0,1,Melo,49,BA,Salvador,Lucas Silveira,35727,Masculino,24,BA,Vitória da Conquista,946,Eletrônicos,Lenovo,2024-12-20,2024-12-30,Pix,Drone,"4489,78"
1,10,Mendonça Machado Ltda.,7,SP,Sorocaba,Isabella Campos,2188,Feminino,41,MG,Uberlândia,112,Eletrônicos,Apple,2023-11-22,2023-11-28,Dinheiro,Celular,"11882,39"
2,1000,Cunha Mendes S.A.,97,BA,Camaçari,Marcela Barbosa,2293,Feminino,47,SP,Sorocaba,283,Alimentos,Del Valle,2023-08-25,2023-08-27,Dinheiro,Suco,"37,08"
3,100001,Nunes,77,MG,Contagem,Ravy Cunha,38559,Feminino,59,RJ,Petrópolis,805,Eletrônicos,Dell,2024-08-03,2024-08-04,Dinheiro,Notebook,"6727,57"
4,100007,Cunha Mendes S.A.,97,BA,Camaçari,Sra. Ana Cecília Pinto,19274,Masculino,27,SP,São Paulo,362,Alimentos,Coca-Cola,2023-02-28,2023-03-08,Pix,Refrigerante,"17,33"

In [80]:
df['Valor de Venda'] = df['Valor de Venda'].str.replace(',', '.').astype(float)
df.head()

,ID Venda,Loja,ID Loja,Estado Loja,Cidade Loja,Nome Cliente,ID Cliente,Sexo,Idade,Estado Cliente,Cidade Cliente,ID Produto,Categoria Produto,Marca,Data da Compra,Data da Entrega,Metodo de Pagamento,Produto,Valor de Venda
0,1,Melo,49,BA,Salvador,Lucas Silveira,35727,Masculino,24,BA,Vitória da Conquista,946,Eletrônicos,Lenovo,2024-12-20,2024-12-30,Pix,Drone,4489.78
1,10,Mendonça Machado Ltda.,7,SP,Sorocaba,Isabella Campos,2188,Feminino,41,MG,Uberlândia,112,Eletrônicos,Apple,2023-11-22,2023-11-28,Dinheiro,Celular,11882.39
2,1000,Cunha Mendes S.A.,97,BA,Camaçari,Marcela Barbosa,2293,Feminino,47,SP,Sorocaba,283,Alimentos,Del Valle,2023-08-25,2023-08-27,Dinheiro,Suco,37.08
3,100001,Nunes,77,MG,Contagem,Ravy Cunha,38559,Feminino,59,RJ,Petrópolis,805,Eletrônicos,Dell,2024-08-03,2024-08-04,Dinheiro,Notebook,6727.57
4,100007,Cunha Mendes S.A.,97,BA,Camaçari,Sra. Ana Cecília Pinto,19274,Masculino,27,SP,São Paulo,362,Alimentos,Coca-Cola,2023-02-28,2023-03-08,Pix,Refrigerante,17.33

In [81]:
df_venda_loja = agrupar_soma(df, 'Loja')
df_venda_loja.head()

                      Loja  Valor de Venda
10  Mendonça Machado Ltda.     11148353.64
11                 Moreira     10298861.57
17                   Sousa     10185505.18
15     Sampaio Viana Ltda.     10064612.43
19                  Vargas      9996259.63

In [82]:
df_venda_loja.tail()

                     Loja  Valor de Venda
8                 Machado      8814422.95
16                 Santos      8704263.74
4        Cunha Gomes - EI      8588818.50
14  Ribeiro Sampaio Ltda.      8533272.70
9                    Melo      8312314.05

In [83]:
dist_venda_loja = calcular_distancia(df_venda_loja)
lim_venda_loja = calcular_limites(df_venda_loja)

mostrar_dist_lim(dist_venda_loja, lim_venda_loja)

Distância: 0.0063822997749274695
Limite Superior: 11669462.979999999
Limite Inferior: 7132590.460000003

In [84]:
outliers_sup_venda_loja = aplicar_loc(df_venda_loja, 'Valor de Venda', lim_venda_loja[0], '>')
outliers_sup_venda_loja

Empty DataFrame
Columns: [Loja, Valor de Venda]
Index: []

In [85]:
outliers_inf_venda_loja = aplicar_loc(df_venda_loja, 'Valor de Venda', lim_venda_loja[1], '<')
outliers_inf_venda_loja

Empty DataFrame
Columns: [Loja, Valor de Venda]
Index: []

In [86]:
df_venda_uf = agrupar_soma(df, 'Estado Loja')
df_venda_uf

  Estado Loja  Valor de Venda
4          SP     58913226.37
2          RJ     50039242.16
3          RS     35200852.28
1          MG     26083883.76
0          BA     17271662.63

In [87]:
dist_venda_uf = calcular_distancia(df_venda_uf)
lim_venda_uf = calcular_limites(df_venda_uf)

mostrar_dist_lim(dist_venda_uf, lim_venda_uf)

Distância: 0.06536549574702503
Limite Superior: 85972279.75999999
Limite Inferior: -9849153.839999992

In [88]:
outliers_venda_uf = aplicar_loc(df_venda_uf, 'Valor de Venda', lim_venda_uf[0], '>')
outliers_venda_uf

Empty DataFrame
Columns: [Estado Loja, Valor de Venda]
Index: []

In [89]:
df_venda_cat_prod = agrupar_soma(df, 'Categoria Produto')
df_venda_cat_prod

  Categoria Produto  Valor de Venda
1       Eletrônicos    121388548.15
3            Móveis     53475497.30
4            Roupas      9740440.91
0         Alimentos      1963297.14
2            Livros       941083.70

In [90]:
dist_venda_cat_prod = calcular_distancia(df_venda_cat_prod)
lim_venda_cat_prod = calcular_limites(df_venda_cat_prod)

mostrar_dist_lim(dist_venda_cat_prod, lim_venda_cat_prod)

Distância: 2.8501104607594185
Limite Superior: 130743797.53999999
Limite Inferior: -75305003.1

In [91]:
outliers_venda_cat_prod = aplicar_loc(df_venda_cat_prod, 'Valor de Venda', lim_venda_cat_prod[0], '>')
outliers_venda_cat_prod

Empty DataFrame
Columns: [Categoria Produto, Valor de Venda]
Index: []

In [92]:
df_venda_prod = agrupar_soma(df, 'Produto')
df_venda_prod.head()

           Produto  Valor de Venda
48         Teclado     13457171.55
12         Celular     13433828.61
20  Fone de Ouvido     12957454.28
31        Notebook     11554446.11
47          Tablet     11278147.89

In [93]:
df_venda_prod.tail()

                   Produto  Valor de Venda
0                     1984        92778.59
35      O Senhor dos Anéis        89607.89
36   Orgulho e Preconceito        88795.81
32       O Código Da Vinci        88746.41
1   A Culpa é das Estrelas        86615.36

In [94]:
dist_venda_prod = calcular_distancia(df_venda_prod)
lim_venda_prod = calcular_limites(df_venda_prod)

mostrar_dist_lim(dist_venda_prod, lim_venda_prod)

Distância: 2.92500013360592
Limite Superior: 13654735.2725
Limite Inferior: -7892502.6275

In [95]:
outliers_venda_prod = aplicar_loc(df_venda_prod, 'Valor de Venda', lim_venda_prod[0], '>')
outliers_venda_prod

Empty DataFrame
Columns: [Produto, Valor de Venda]
Index: []